apiVersion: "ryax.tech/v1"
kind: Functions
spec:
  id: ner-bert-base
  human_name: Named Entity Recognition (BERT for token classification)
  type: python3
  version: "1.0"
  logo: logo.png
  detail: "Named Entity Recognition (NER) on text samples. More detail at: https://huggingface.co/transformers/task_summary.html#named-entity-recognition"
  inputs:
  - help: List of dictionaries with a key called text 
    human_name: Path to the data
    name: data_path
    type: file
  outputs:
  - help: Input data plus predictions
    human_name: Predictions
    name: predictions
    type: file
