apiVersion: "ryax.tech/v1"
kind: Functions
spec:
  id: flow-mapper
  human_name: Flow Mapper Component
  type: python3
  version: "1.0"
  logo: "logo.png"
  detail: "First part of landmapR in python"
  inputs:
  - help: "DEM file"
    human_name: "Elevation map"
    name: file
    type: "file"
  - help: "rows number"
    human_name: "Number of rows of file"
    name: nrow
    type: "integer"
  - help: "cols number"
    human_name: "Number of columns of file"
    name: ncol
    type: "integer"
  outputs:
  - help: "one of output files"
    human_name: "An output"
    name: db_ilocal
    type: "file"